#pragma once

#include <QObject>
#include <QString>

class ThemeService : public QObject {
  Q_OBJECT
  Q_CLASSINFO("D-Bus Interface", "org.ciel.Theme")

  Q_PROPERTY(
      bool DarkMode READ isDarkMode WRITE SetDarkMode NOTIFY ThemeChanged)
  Q_PROPERTY(QString AccentColor READ accentColor WRITE SetAccentColor NOTIFY
                 ThemeChanged)
  Q_PROPERTY(bool ReducedMotion READ isReducedMotion WRITE SetReducedMotion
                 NOTIFY ThemeChanged)

public:
  explicit ThemeService(QObject *parent = nullptr);

  bool isDarkMode() const { return m_darkMode; }
  QString accentColor() const { return m_accentColor; }
  bool isReducedMotion() const { return m_reducedMotion; }

public slots:
  // PascalCase matches org.ciel.Theme.xml exactly
  void SetDarkMode(bool enabled);
  void SetAccentColor(const QString &hexColor);
  void SetReducedMotion(bool enabled);

signals:
  // PascalCase signal parameters generated by qdbusxml2cpp:
  // ThemeChanged(bool DarkMode, const QString &AccentColor, bool ReducedMotion)
  void ThemeChanged(bool DarkMode, const QString &AccentColor,
                    bool ReducedMotion);

private:
  void loadConfig();
  void saveConfig();
  QString configFilePath() const;

  bool m_darkMode = true;
  QString m_accentColor = "#0A84FF";
  bool m_reducedMotion = false;
};
